name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH  # Add Poetry to PATH

      # Verify Poetry Installation
      - name: Check Poetry version
        run: poetry --version

      # Install dependencies
      - name: Install dependencies
        run: poetry install

      # Run tests (if applicable)
      - name: Run tests
        run: poetry run pytest
